services:
  - type: web
    name: 9router
    runtime: node
    plan: free
    region: singapore # Khu vực Singapore ping về Việt Nam nhanh nhất (~30ms)
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/version
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: NODE_ENV
        value: production
      - key: ENABLE_REQUEST_LOGS
        value: "false"
      - key: OBSERVABILITY_ENABLED
        value: "false"
      - key: JWT_SECRET
        generateValue: true
      - key: INITIAL_PASSWORD
        value: admin123456
      - key: ANTIGRAVITY_BASE_URL
        value: https://9router-proxy.nhathoangnguyen1748.workers.dev

